<?php require_once 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<div class="col-md-10 mx-auto col-lg-5">
  <form class="p-4 p-md-5 border rounded-3 bg-body-tertiary" method='post' action='logearse'>
    <div class="form-floating mb-3">
      <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" _mstplaceholder="299455" _msthash="23">
      <label for="floatingInput" _msttexthash="868153" _msthash="24">Dirección de correo electrónico</label>
    </div>
    <div class="form-floating mb-3">
      <input type="password" class="form-control" id="clave" name="clave" placeholder="Contraseña" _mstplaceholder="117572" _msthash="25">
      <label for="floatingPassword" _msttexthash="182013" _msthash="26">Contraseña</label>
    </div>
    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"><font _mstmutation="1" _msttexthash="172679" _msthash="27"> Recuérdame </font></label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit" _msttexthash="72618" _msthash="28">Ingresar</button>
    <hr class="my-4">
    
    <br>
    <a class="btn btn-secondary" href="mostrarRegistrarse" role="button">Registrarse</a>
  </form>
</div>

<?php require_once 'templates/layout/header.phtml'?>