<?php require_once 'layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form class="row g-3" method='post' action='cargarEditarUsuario'>
  <div class="col-md-4">
    <label for="validationServer01" class="form-label">Nombre</label>
    <input type="text" name="nombre" class="form-control is-valid" id="validationServer01" placeholder="<?php $this->user->nombre?>">
    <div class="valid-feedback">
      Looks good!
    </div>
  </div>
  <div class="col-md-4">
    <label for="validationServer02" class="form-label">Email</label>
    <input type="email" name="email" class="form-control is-valid" id="inputEmail4" placeholder="<?php $this->user->email?>">
  </div>
  <div class="col-md-6">
    <label for="validationServer03" class="form-label">Clave vieja</label>
    <input type="password" name="claveVieja" class="form-control is-invalid" id="clave" name="clave" placeholder="Contraseña" _mstplaceholder="117572" _msthash="25" aria-describedby="validationServer03Feedback">
    <div id="validationServer03Feedback" class="invalid-feedback">
      Please provide a valid city.
    </div>
  </div>
  <div class="col-md-3">
    <label for="validationServer05" class="form-label" _msttexthash="182013" _msthash="26">Clave nueva</label>
    <input type="password" name="claveNueva" class="form-control is-invalid" id="clave" name="clave" placeholder="Contraseña" _mstplaceholder="117572" _msthash="25" aria-describedby="validationServer03Feedback">
    <div id="validationServer05Feedback" class="invalid-feedback">
      Please provide a valid zip.
    </div>
  </div>
  
  <div class="col-12">
    <button class="btn btn-primary" type="submit">Subir formulario</button>
  </div>
</form>



<?php require_once 'layout/header.phtml' ?>