<?php require_once 'layout/header.phtml'; ?>
<div class="container row text-center">
    <?php
    $cont = 1;
     foreach($vuelos as $vuelo):?>
        <div class="card" style="width: 18rem;">
            <img src="<?= htmlspecialchars($vuelo->url_Imagen) ?>" class="card-img-top rounded mx-auto d-block" alt="...">
            <div class="card-body">
                <h5 class="card-title"><?= htmlspecialchars($vuelo->salida) ?> | <?= htmlspecialchars($vuelo->destino) ?> </h5>
                <p class="card-text">Precio por persona : $<?= $vuelo->precio ?></p>
                

                <div class="btn-group" role="group" aria-label="Basic outlined example">
                    <a href="Vuelos/<?= $vuelo->id ?>" class="btn btn-success" role="button">Ver mas</a>
                    <?php if($this->user): ?>
                        <a href="MostrarEditar/Vuelo/<?= $vuelo->id ?>" class="btn btn-primary" role="button">Editar</a>
                        <a href="Eliminar/Vuelo/<?= $vuelo->id ?>" class="btn btn-danger" role="button">Eliminar</a>
                    <?php endif ?>

                </div>
            </div>
        </div>

    <?php
    $cont++;
    endforeach ?>
    <?php if($this->user): ?>
        <div class="card" style="width: 18rem;">
            <a class="btn" href="Insertar/Vuelo" role="button">
                <svg xmlns="http://www.w3.org/2000/svg" width="auto" height="320" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4"/>
                </svg>
            </a>
        </div>
    <?php endif ?>
</div>
<?php require_once 'layout/footer.phtml'; ?>