<?php require_once 'layout/header.phtml'; ?>
<main>
<div class="container overflow-hidden text-center">
    <?php foreach($vuelos as $vuelo):?>
        <div class="card" style="width: 18rem;">
            <img src="<?= htmlspecialchars($vuelo->url_Imagen) ?>" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title"><?= htmlspecialchars($vuelo->salida) ?> | <?= htmlspecialchars($vuelo->destino) ?> </h5>
                <p class="card-text">Precio por persona : $<?= $vuelo->precio ?></p>
                
                <div class="accordion" id="accordionExample">
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                                Ver mas...
                            </button>
                        </h2>
                        <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                            <div class="accordion-body">
                                <p>Dia: <?= htmlspecialchars($vuelo->fecha) ?></p>
                                <p>Avion: <?= htmlspecialchars($vuelo->avion) ?></p>
                                <p>Hora salida: <?=date('H:i', strtotime($vuelo->hs_salida)) ?> </p> 
                                <p>Hora llegada: <?= date('H:i', strtotime($vuelo->hs_llegada))?></p>

                                <a href="reservarVuelo/<?= $this->user->id?>/<?= $vuelo->id ?>" class="btn btn-primary" role="button">Reservar</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    <?php endforeach ?>
</div>
</main>
<?php require_once 'layout/footer.phtml'; ?>