<?php 
require_once 'layout/header.phtml';?>
<?php if($vuelo){?>
    <div class="card" style="width: 18rem;">
        <img src="<?= htmlspecialchars($vuelo->url_Imagen)?>" class="card-img-top rounded mx-auto d-block" alt="...">
        <div class="card-body">
            <h5 class="card-title"><?= htmlspecialchars($vuelo->salida) ?> | <?= htmlspecialchars($vuelo->destino) ?> </h5>
            <p class="card-text">Precio por persona : $<?= $vuelo->precio ?></p>
            <p>Dia: <?= htmlspecialchars($vuelo->fecha) ?></p>
            <p>Avion: <?= htmlspecialchars($vuelo->avion) ?></p>
            <p>Hora salida: <?=date('H:i', strtotime($vuelo->hs_salida)) ?> </p> 
            <p>Hora llegada: <?= date('H:i', strtotime($vuelo->hs_llegada))?></p>

            <a href="eliminarVuelo/<?= $this->user->id ?>" class="btn btn-primary" role="button">Eliminar</a>

        </div>
    </div>
<?php } else {?>
    <h5>El usuario no tiene vuelos.</h5>
    <?php }?>
<?php require_once 'layout/header.phtml';?>