<?php 
require_once 'layout/header.phtml';?>

<div>
    <h3>Usuario: </h3>

    <div class="col-md-6">
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">
                <a href="mostrarModificarUsuario">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"></path>
                    </svg>
                </a>
            </span>
            <label class="form-control" aria-describedby="basic-addon1"><?=$usuario->nombre?></label>
        </div>
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">
                <a href="mostrarModificarUsuario">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"></path>
                    </svg>
                </a>
            </span>
            <label class="form-control" aria-describedby="basic-addon1"><?=$usuario->email?></label>
        </div>
    </div>

    </div>

</div>

<h3>Vuelos:</h3>
<?php if($vuelo){?>
    <div class="card" style="width: 18rem;">
        <img src="<?= htmlspecialchars($vuelo->url_Imagen)?>" class="card-img-top rounded mx-auto d-block" alt="...">
        <div class="card-body">
            <h5 class="card-title"><?= htmlspecialchars($vuelo->salida) ?> | <?= htmlspecialchars($vuelo->destino) ?> </h5>
            <p class="card-text">Precio por persona : $<?= $vuelo->precio ?></p>
            <p>Dia: <?= htmlspecialchars($vuelo->fecha) ?></p>
            <p>Avion: <?= htmlspecialchars($vuelo->avion) ?></p>
            <p>Hora salida: <?=date('H:i', strtotime($vuelo->hs_salida)) ?> </p> 
            <p>Hora llegada: <?= date('H:i', strtotime($vuelo->hs_llegada))?></p>

            <a href="eliminarVuelo/<?= $this->user->id ?>" class="btn btn-primary" role="button">Eliminar</a>

        </div>
    </div>
<?php } else {?>
    <div class="alert alert-info" role="alert">
        <h5>El usuario no tiene vuelos.</h5>
    </div>
    <?php }?>
<?php require_once 'layout/header.phtml';?>